language: node_js

env:
  matrix:
    secure: gAExwu6JW0fUr8QTrUIJbCGGWeNHDKGqjn4PMDmL+tbV6sH1Fs/hK8jVN41jwlmzvaaeD/WsPTBncDT1H/Bgp0prvLGmgSQJknsXmz0IzSe5OdnJ4pBk//Qy+MZk0+G+qrUTXnaC9n6FSj4LXke5L0JNWXAF79T7u+eCqWKievfPto/BlurSYIE02a6JdL42xS3wJbVgFB0pZHjOIySRJzafKrGZh8cJGoM5GqX0IY9tEbCu8h0fIsDUcxgpLhTtZYxGY23pl9rysixUSvSGIJHela6nno7EM4QB5+ahhwR4amj527BQ6pxb80M5uZ0o8VAuQPNMJvl5IRUgRlyKieURDH6J3hI7cjW+HVaJUQN/hX21r6YlsCKHtg7S7ESgad33wI5ZP1XXjJwV/UiPLyTHjlWBx8VE9vtAvVDV4rm0y3XSA8YpCZ8fVp6e9fLQ01HRQK8J3RNXu3ySRksQ8DDe0XSVO91HB4lL5rYfx/PnifoQqNzxctoM1yx855x86Tt6qXn10qWxx4cRjgmQBYoqIz7cISr2JeiEO3/xU6x/gGKFvttRLAQZZF9SxCLBQ86SieF8BiMz/59DJEvb1jujWbygXQ4X8Qgvv6TTLtZ4o559Tho/4zd09uHoda+Pw5EGZkymUzFQBdvErdjPTmptpQhj89e03qrsSDI16XA=

script:
- pushd functions && npm install && npm run build && popd

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    repo: joernahrens/groc-list-backend
    branch: master

notifications:
  slack:
    secure: UDCA/aJptgvAnSY8s9m0gTqkaHfK+/ixF96KwQcX0sZNyWbiGsM74Z/7NJO4yT/uvk0nRLaBpvAwGjapQ9Ns38MsVIi5gGmqEtXVLMnTSiS1/uSO/KoHqIcQGgFGTViZOgvgLoAsA39inq3vvqu6U9HVe0K1asBbiKEni6mBCiwl/ySKc+KOeeiU8LK8Dtc3X+NZDFvZRyKCduXk7+JeViiH3tpn/QxZ5ythHGuW4ZzjbzpwUhkU2l6Ex34sMQUldx5R8pMi9QnVM9ZHLXBjRLO+qKW6TSZyaKNbcS2LzteUb6oircKZ3MPVZ9/dfdCCcOBof9MTMgI98B2DSlBvBWw2/Ydpj3wSnvPnRjXISlMFH4ixhrcNuUNyMGIl8RMwttU9JyVR7lLGWS7dRd8yfaAJAiVMjlEOyD5DT9y1XJ8d5xR8XEtzZgS+zGQ/aJYZz7tqZenfwH195n+GqYPMnyLeR0SwfdRDQU+pmj2LaD06ddYEt6UNUsK35hq1J5XlvPf6au+3Q3nVljguxQQX09842ec/gOJLs4EFtLkfs0ZxUjbY79rSLJFdNg7K8BeXA3INdWsARYBVA2XKLr/CGlq4A4XevzxgOr9u/h9KiMz4ngUan4mofdM4uHqPjMHDeC2WiYnbIsYvnzdApTTGiIlQNx/8MIXTaToM7F9xHyk=
